### PR TITLE
Make tox env be created errorless again

### PR DESCRIPTION
**Pull request by anxolerd**
- Cleanup tox.ini -- remove duplicate install_command from descendant testenv
- Use stable versions of packages when testing

### CODE REVIEW

**Review by webknjaz — COMMENTED** [review]
Try simplifying it to look [like this](https://github.com/cherrypy/cherrypy/blob/master/tox.ini) and probably wipe `requirements.txt`

**Comment by webknjaz** [comment]
@anxolerd is this still relevant?

**Comment by anxolerd** [comment]
Well, it might be partially. I'd better check the current codebase.

**Comment by anxolerd** [comment]
outdated

**Comment by webknjaz** [comment]
There's an intermittent issue with smtp tests under python 3.6

**Comment by webknjaz** [comment]
Ref: #8

**Pull request closed without merging**
